# -----------------------------------------------------------------------------
# ESPHome config file for the balcony sensors module
# CAH 2019-03-17
#
# DHT22     : D5
# DSB18B20  : D7 (balcony)
# DSB18B20  : D6 (living-room)
# -----------------------------------------------------------------------------

substitutions:
  node_hostname: balcony_sensors
  node_name: "Balcony"

packages:
  device_base: !include common/device_base.yaml
  plaform:  !include common/nodemcu.yaml



sensor:

  - platform: dht
    pin: D5
    model: DHT22
    temperature:
      name: "${node_name} Temperature"
    humidity:
      name: "${node_name} Humidity"
    update_interval: 30s
