# -----------------------------------------------------------------------------
# ESPHome config file for the balcony sensors module
# CAH 2019-03-17
#
# DHT22     : D5
# DSB18B20  : D7 (balcony)
# DSB18B20  : D6 (living-room)
# -----------------------------------------------------------------------------

esphome:
  name: balcony_sensors
  platform: ESP8266
  board: nodemcuv2


wifi:
  networks:
    - ssid: !secret wifi_ssid_1
      password: !secret wifi_password_1
    - ssid: !secret wifi_ssid_2
      password: !secret wifi_password_2
    - ssid: !secret wifi_ssid_3
      password: !secret wifi_password_3
  power_save_mode: light
  ap:
    ssid: Balcony 01 Fallback Hotspot
    password: !secret ap_password

captive_portal:

ota:
  safe_mode: True
  password: !secret ota_password

logger:
  level: DEBUG
  
status_led:
  pin:
    number: D4
    inverted: True

api:


sensor:

  - platform: dht
    pin: D5
    model: DHT22
    temperature:
      name: "Balcony Temperature"
    humidity:
      name: "Balcony Humidity"
    update_interval: 30s
    
  - platform: wifi_signal
    name: "Balcony WiFi Signal"

  - platform: uptime
    name: "Balcony Uptime"

text_sensor:
  - platform: version
    name: "ESPHome Version"

switch:
  - platform: restart
    name: "Balcony Restart"
