# -----------------------------------------------------------------------------
# ESPHome config file for the second version of the Balcony 02 sensors module
# CAH 2019-11-01
#
# This board has a BMP280 temperature and barometric pressure sensor,
# a PIR motion sensor and an SSD1306 monochrome OLED display; BME280 and the 
# SSD1306 are connected to the same I2C bus, and the PIR has its own GPIO.
#
#   BMP280      I2C bus
#   SSD1306     I2C bus
#   PIR         GPIO-05 / D1
#   I2C SDA     GPIO-12 / D6
#   I2C SLC     GPIO-13 / D7
#   Status      GPIO-O2 / D4 (built-in LED)
#   DHT-22      GPIO-14 / D5
#   DHT-22      GPIO-04 / D2
#
# A simple automation is defined in the device to display the sensor data
# for a short period of time when motion is detected by the PIR.
#
# Tutorials:
#
#   - https://esphome.io/cookbook/bme280_environment.html
#   - https://esphome.io/cookbook/display_time_temp_oled.html
#   - https://esphome.io/cookbook/pir.html
# 
# TODO: read '/mnt/d/Users/heckler/Dropbox/Home files/Projetos Arduino e ESP32/Home automation/sources'
#
# -----------------------------------------------------------------------------

esphome:
  name: balcony_sensors_02
  platform: ESP8266
  board: nodemcuv2
  on_boot:
    then:
      - display.page.show: page2

wifi:
  networks:
    - ssid: !secret wifi_ssid_1
      password: !secret wifi_password_1
    - ssid: !secret wifi_ssid_2
      password: !secret wifi_password_2
    - ssid: !secret wifi_ssid_3
      password: !secret wifi_password_3
  power_save_mode: none
  reboot_timeout: 300s
  ap:
    ssid: Balcony 02 02 Fallback Hotspot
    password: !secret ap_password

captive_portal:

ota:
  safe_mode: True
  password: !secret ota_password

logger:
  level: DEBUG
  
status_led:
  pin:
    number: D4
    inverted: True

api:

# I2C bus: https://esphome.io/components/i2c.html#i2c
i2c:
  sda: D6
  scl: D7
  scan: True
  id: bus_a

# SSD1306 display: https://esphome.io/components/display/ssd1306.html
display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    id: my_display
    i2c_id: bus_a
    address: 0x3C
    rotation: 180
    update_interval: 2s
    pages:
      - id: page1
        lambda: |-
          it.rectangle(0, 0, 128, 64);
          it.printf(5, 22, id(font1), TextAlign::BOTTOM_LEFT, "T");
          it.printf(5, 42, id(font1), TextAlign::BOTTOM_LEFT, "H");
          it.printf(5, 62, id(font1), TextAlign::BOTTOM_LEFT, "P");
          it.printf(70, 22, id(font1), TextAlign::BOTTOM_RIGHT, "23.4");
          it.printf(76, 18, id(font2), TextAlign::BOTTOM_LEFT, "°C");
          it.printf(70, 42, id(font1), TextAlign::BOTTOM_RIGHT, "65.8");
          it.printf(78, 38, id(font2), TextAlign::BOTTOM_LEFT, "%%");
          it.printf(70, 62, id(font1), TextAlign::BOTTOM_RIGHT, "1042");
          it.printf(78, 58, id(font2), TextAlign::BOTTOM_LEFT, "hPa");
          it.printf(120, 22, id(font1), TextAlign::BOTTOM_RIGHT, "/");
          it.printf(120, 42, id(font1), TextAlign::BOTTOM_RIGHT, "=");
          it.printf(120, 62, id(font1), TextAlign::BOTTOM_RIGHT, "\\");
      - id: page2
        lambda: |-
          it.fill(COLOR_OFF);


font:
  - file: 'fonts/FreeSans.ttf'
    id: font1
    size: 18
    glyphs: '!"%()+,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz/\='
  - file: 'fonts/FreeSans.ttf'
    id: font2
    size: 10
    

binary_sensor:
  - platform: gpio
    pin: D1
    name: "PIR Sensor"
    device_class: motion
    on_press:
      then:
        - display.page.show: page1
        - component.update: my_display
        - delay: 30s
        - display.page.show: page2


sensor:

  # BMP280: https://esphome.io/components/sensor/bmp280.html
  - platform: bmp280
    i2c_id: bus_a
    temperature:
      name: "Balcony 02 Temperature"
      oversampling: 16x
    pressure:
      name: "Balcony 02 Pressure"
    address: 0x77
    update_interval: 60s

  # # DHT-22 on the outside (balcony): 
  # # only collect humidity (temperature comes from the BMP280)
  # - platform: dht
  #   pin: D2
  #   humidity:
  #     name: "Balcony 02 Humidity"
  #   update_interval: 60s

  # # DHT-22 on the inside (living room)
  # - platform: dht
  #   pin: D5
  #   temperature:
  #     name: "Living Room 02 Temperature"
  #   humidity:
  #     name: "Living Room 02 Humidity"
  #   update_interval: 60s

  - platform: wifi_signal
    name: "Balcony 02 WiFi Signal"

  - platform: uptime
    name: "Balcony 02 Uptime"
    id: uptime_sensor


text_sensor:
  - platform: version
    name: "Balcony 02 Version"


switch:
  - platform: restart
    name: "Balcony 02 Restart"
