# -----------------------------------------------------------------------------
# ESPHome config file for the ESP32Cam module 02
# CAH 2019-10-27
#
# LED on the backside of the board:   GPIO33 (inverted)
# LED on the front of the board:      GPIO4
#
# -----------------------------------------------------------------------------

substitutions:
  node_hostname: esp32cam02
  node_name: "ESP32Cam 02"

packages:
  device_base: !include common/device_base.yaml
  plaform: !include common/esp32cam.yaml
