# -----------------------------------------------------------------------------
# ESPHome config file for the fireplace accent light (Sonoff basic RF)
# CAH 2020-07-19
#
# For the initial reflashing with ESPHome, refer to <docs/flashing_sonoff_basic.md>
# -----------------------------------------------------------------------------

substitutions:
  node_hostname: fireplace_light
  node_name: "Fireplace Light"
  switch_icon: "mdi:fireplace"

packages:
  device_base: !include common/device_base.yaml
  plaform:  !include common/sonoff_basic.yaml
