# -----------------------------------------------------------------------------
# ESPHome config file for the balcony irrigation pump (Sonoff Basic)
#
# CAH 2021-10-10
#
# +----------------------------------------+
# | Description and basic information      |
# +----------------------------------------+
#
# This is a Sonoff Basic driving a simple water pump, which pushes water though
# a water line to drippers on the differt flower pots on the balcony.
#

esphome:
  name: irrigation_pump
  platform: ESP8266
  board: esp8285
  arduino_version: 2.4.2

wifi:
  networks:
    - ssid: !secret wifi_ssid_1
      password: !secret wifi_password_1
    - ssid: !secret wifi_ssid_2
      password: !secret wifi_password_2
    - ssid: !secret wifi_ssid_3
      password: !secret wifi_password_3

captive_portal:

ota:
  safe_mode: True
  password: !secret ota_password

api:

logger:
  level: DEBUG

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Irrigation Pump Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    icon: mdi:water-pump
    name: "Irrigation Pump Relay"
    pin: GPIO12
    id: relay
  - platform: restart
    name: "Irrigation Pump Restart"

status_led:
  pin:
    number: GPIO13
    inverted: yes

sensor:

  - platform: uptime
    name: "Irrigation Pump Uptime"
    id: uptime_sensor

text_sensor:
  - platform: version
    name: "Irrigation Pump Version"
