# -----------------------------------------------------------------------------
# ESPHome config file for the balcony irrigation pump (Sonoff Basic)
#
# CAH 2021-10-10
#
# +----------------------------------------+
# | Description and basic information      |
# +----------------------------------------+
#
# This is a Sonoff Basic driving a simple water pump, which pushes water though
# a water line to drippers on the differt flower pots on the balcony.
#

substitutions:
  node_hostname: irrigation_pump
  node_name: "Irrigation Pump"
  switch_icon: "mdi:water-pump"

packages:
  device_base: !include common/device_base.yaml
  plaform:  !include common/sonoff_basic.yaml
