# -----------------------------------------------------------------------------
# Quick test for the new PIR sensors
# When motion is detected, turn-on the embedded LED for 5 seconds

# CAH 2019-11-03
#
#   PIR         GPI13 / D7
#
# Tutorial: https://esphome.io/cookbook/pir.html
# 
# -----------------------------------------------------------------------------


esphome:
  name: pir_test
  platform: ESP8266
  board: nodemcuv2


wifi:
  networks:
    - ssid: !secret wifi_ssid_1
      password: !secret wifi_password_1
    - ssid: !secret wifi_ssid_2
      password: !secret wifi_password_2
    - ssid: !secret wifi_ssid_3
      password: !secret wifi_password_3
  power_save_mode: none
  reboot_timeout: 300s
  ap:
    ssid: PIR Test Fallback Hotspot
    password: !secret ap_password

captive_portal:

ota:
  safe_mode: True
  password: !secret ota_password

logger:
  level: DEBUG
  

api:


binary_sensor:
  - platform: gpio
    pin: D7
    name: "PIR Sensor"
    device_class: motion
    on_press:
      then:
        - switch.turn_on: pir_led
        - delay: 5s
        - switch.turn_off: pir_led


sensor:

  - platform: wifi_signal
    name: "PIR WiFi Signal"

  - platform: uptime
    name: "PIR Uptime"


text_sensor:
  - platform: version
    name: "PIR Version"


switch:

  - platform: restart
    name: "PIR Restart"

  - platform: gpio
    pin: D4
    name: "PIR LED Out"
    inverted: True
    id: pir_led
