# -----------------------------------------------------------------------------
# Quick test for the new PIR sensors
# When motion is detected, turn-on the embedded LED for 5 seconds
#
# CAH 2019-11-03
#
#   PIR         GPI13 / D7
#
# Tutorial: https://esphome.io/cookbook/pir.html
# 
# -----------------------------------------------------------------------------


substitutions:
  node_hostname: pir_test
  node_name: "PIR Test"

packages:
  device_base: !include common/device_base.yaml
  plaform:  !include common/nodemcu.yaml



binary_sensor:
  - platform: gpio
    pin: D7
    name: "${node_name} Sensor"
    device_class: motion
    on_press:
      then:
        - switch.turn_on: pir_led
        - delay: 5s
        - switch.turn_off: pir_led


switch:
  - platform: gpio
    pin: D4
    name: "${node_name} LED"
    inverted: True
    id: pir_led
