# -----------------------------------------------------------------------------
# Uptime test, to see how the node behaves before it stops responding.
#
# CAH 2019-11-04
#
# Conclusion: setting power_save_mode:light under wifi was causing the ESP8266
# to lose connection with the network after a few seconds of activity; setting
# it to none had the result of the device behaving in a stable manner again.
# -----------------------------------------------------------------------------


substitutions:
  node_hostname: uptime_test
  node_name: "Uptime Test"

packages:
  device_base: !include common/device_base.yaml
  plaform:  !include common/nodemcu.yaml

