# -----------------------------------------------------------------------------
# ESPHome config file for the wake-up lights (Sonoff B1)
# CAH 2022-04-17
#
# For the initial reflashing with ESPHome, refer to <docs/flashing_sonoff_b1.md>
# -----------------------------------------------------------------------------

substitutions:
  node_hostname: wakeup_light_01r
  node_name: "Wake-up Light 01-R"

packages:
  device_base: !include common/device_base.yaml
  plaform:  !include common/sonoff_b1.yaml
